// <auto-generated />
using System;
using Ambev.DeveloperEvaluation.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ambev.DeveloperEvaluation.ORM.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20250324202359_CreatedEntities")]
    partial class CreatedEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.CartProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartProducts");
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Discounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            MaxQuantity = 9,
                            MinQuantity = 4,
                            Percentage = 10m
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            MaxQuantity = 20,
                            MinQuantity = 10,
                            Percentage = 20m
                        });
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("RatingId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RatingId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Eletronicos",
                            Image = "eletronico1.jpg",
                            Price = 1200.00m,
                            Quantity = 20,
                            RatingId = 1,
                            Title = "Smartphone Eletronico 1"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Eletronicos",
                            Image = "eletronico2.jpg",
                            Price = 1300.00m,
                            Quantity = 18,
                            RatingId = 2,
                            Title = "Smartphone Eletronico 2"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Eletronicos",
                            Image = "eletronico3.jpg",
                            Price = 2500.00m,
                            Quantity = 10,
                            RatingId = 3,
                            Title = "Smart TV Eletronico 3"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Eletronicos",
                            Image = "eletronico4.jpg",
                            Price = 3000.00m,
                            Quantity = 8,
                            RatingId = 4,
                            Title = "Notebook Eletronico 4"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Eletronicos",
                            Image = "eletronico5.jpg",
                            Price = 900.00m,
                            Quantity = 12,
                            RatingId = 5,
                            Title = "Tablet Eletronico 5"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Eletronicos",
                            Image = "eletronico6.jpg",
                            Price = 1500.00m,
                            Quantity = 5,
                            RatingId = 6,
                            Title = "Câmera Eletronico 6"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Eletronicos",
                            Image = "eletronico7.jpg",
                            Price = 200.00m,
                            Quantity = 25,
                            RatingId = 7,
                            Title = "Fone de Ouvido Eletronico 7"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Eletronicos",
                            Image = "eletronico8.jpg",
                            Price = 350.00m,
                            Quantity = 30,
                            RatingId = 8,
                            Title = "Smartwatch Eletronico 8"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Eletronicos",
                            Image = "eletronico9.jpg",
                            Price = 2800.00m,
                            Quantity = 7,
                            RatingId = 9,
                            Title = "Console Eletronico 9"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Eletronicos",
                            Image = "eletronico10.jpg",
                            Price = 800.00m,
                            Quantity = 10,
                            RatingId = 10,
                            Title = "Monitor Eletronico 10"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Bebidas",
                            Image = "bebida1.jpg",
                            Price = 5.00m,
                            Quantity = 50,
                            RatingId = 11,
                            Title = "Refrigerante Bebida 1"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Bebidas",
                            Image = "bebida2.jpg",
                            Price = 5.50m,
                            Quantity = 60,
                            RatingId = 12,
                            Title = "Refrigerante Bebida 2"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Bebidas",
                            Image = "bebida3.jpg",
                            Price = 8.00m,
                            Quantity = 40,
                            RatingId = 13,
                            Title = "Suco Bebida 3"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Bebidas",
                            Image = "bebida4.jpg",
                            Price = 10.00m,
                            Quantity = 100,
                            RatingId = 14,
                            Title = "Cerveja Bebida 4"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Bebidas",
                            Image = "bebida5.jpg",
                            Price = 50.00m,
                            Quantity = 30,
                            RatingId = 15,
                            Title = "Vinho Bebida 5"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Bebidas",
                            Image = "bebida6.jpg",
                            Price = 2.00m,
                            Quantity = 80,
                            RatingId = 16,
                            Title = "Água Bebida 6"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Bebidas",
                            Image = "bebida7.jpg",
                            Price = 7.50m,
                            Quantity = 35,
                            RatingId = 17,
                            Title = "Suco Bebida 7"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Bebidas",
                            Image = "bebida8.jpg",
                            Price = 6.00m,
                            Quantity = 55,
                            RatingId = 18,
                            Title = "Refrigerante Bebida 8"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Bebidas",
                            Image = "bebida9.jpg",
                            Price = 12.00m,
                            Quantity = 90,
                            RatingId = 19,
                            Title = "Cerveja Bebida 9"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Bebidas",
                            Image = "bebida10.jpg",
                            Price = 2.50m,
                            Quantity = 70,
                            RatingId = 20,
                            Title = "Água Bebida 10"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Decoração",
                            Image = "decoracao2.jpg",
                            Price = 55.00m,
                            Quantity = 20,
                            RatingId = 22,
                            Title = "Vaso Decoracao 2"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Decoração",
                            Image = "decoracao3.jpg",
                            Price = 120.00m,
                            Quantity = 10,
                            RatingId = 23,
                            Title = "Quadro Decoracao 3"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Decoração",
                            Image = "decoracao4.jpg",
                            Price = 150.00m,
                            Quantity = 8,
                            RatingId = 24,
                            Title = "Relógio Decoracao 4"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Decoração",
                            Image = "decoracao5.jpg",
                            Price = 80.00m,
                            Quantity = 12,
                            RatingId = 25,
                            Title = "Luminária Decoracao 5"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Decoração",
                            Image = "decoracao6.jpg",
                            Price = 35.00m,
                            Quantity = 30,
                            RatingId = 26,
                            Title = "Almofada Decoracao 6"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Decoração",
                            Image = "decoracao7.jpg",
                            Price = 200.00m,
                            Quantity = 5,
                            RatingId = 27,
                            Title = "Espelho Decoracao 7"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Decoração",
                            Image = "decoracao8.jpg",
                            Price = 100.00m,
                            Quantity = 7,
                            RatingId = 28,
                            Title = "Cortina Decoracao 8"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Decoração",
                            Image = "decoracao9.jpg",
                            Price = 750.00m,
                            Quantity = 3,
                            RatingId = 29,
                            Title = "Sofá Decoracao 9"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Decoração",
                            Image = "decoracao10.jpg",
                            Price = 350.00m,
                            Quantity = 4,
                            RatingId = 30,
                            Title = "Mesa Decoracao 10"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Decoração",
                            Image = "decoracao1.jpg",
                            Price = 45.00m,
                            Quantity = 15,
                            RatingId = 21,
                            Title = "Vaso Decoracao 1"
                        });
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<float>("Rate")
                        .HasPrecision(3, 2)
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Ratings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 2,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 3,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 4,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 5,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 6,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 7,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 8,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 9,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 10,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 11,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 12,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 13,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 14,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 15,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 16,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 17,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 18,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 19,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 20,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 21,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 22,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 23,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 24,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 25,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 26,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 27,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 28,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 29,
                            Count = 10,
                            Rate = 5f
                        },
                        new
                        {
                            Id = 30,
                            Count = 10,
                            Rate = 5f
                        });
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SaleNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SaleItems", (string)null);
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Cart", b =>
                {
                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.CartProduct", b =>
                {
                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.Cart", "Cart")
                        .WithMany("Products")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Product", b =>
                {
                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.Rating", "Rating")
                        .WithMany()
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.SaleItem", b =>
                {
                    b.HasOne("Ambev.DeveloperEvaluation.Domain.Entities.Sale", null)
                        .WithMany("Items")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Ambev.DeveloperEvaluation.Domain.Entities.Sale", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
